// <auto-generated />
using System;
using EyRiskScreening.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EyRiskScreening.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EyRiskScreening.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EyRiskScreening.Infrastructure.Persistence.Screening.Entities.ScreeningMatchEntity", b =>
                {
                    b.Property<long>("ScreeningMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ScreeningMatchId"));

                    b.Property<decimal>("EditSimilarity")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsExactMatch")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long>("ScreeningSourceResultId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("TokenSimilarity")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ScreeningMatchId");

                    b.HasIndex("ScreeningSourceResultId", "SortOrder")
                        .IsUnique();

                    b.ToTable("ScreeningMatches", "screening", t =>
                        {
                            t.HasCheckConstraint("CK_ScreeningMatches_ExactScore", "[IsExactMatch] = 0 OR [OverallScore] = 100");

                            t.HasCheckConstraint("CK_ScreeningMatches_FieldsJson", "ISJSON([FieldsJson]) = 1 AND DATALENGTH([FieldsJson]) <= 131072");

                            t.HasCheckConstraint("CK_ScreeningMatches_Scores", "[OverallScore] BETWEEN 0 AND 100 AND [TokenSimilarity] BETWEEN 0 AND 100 AND [EditSimilarity] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_ScreeningMatches_SortOrder", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("EyRiskScreening.Infrastructure.Persistence.Screening.Entities.ScreeningRunEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("NormalizedEntityName")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalHits")
                        .HasColumnType("int");

                    b.Property<int>("TotalReturnedResults")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RunId");

                    b.HasIndex("RequestedAtUtc")
                        .IsDescending();

                    b.HasIndex("UserId", "RequestedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("ScreeningRuns", "screening", t =>
                        {
                            t.HasCheckConstraint("CK_ScreeningRuns_Counts", "[TotalHits] >= 0 AND [TotalReturnedResults] >= 0 AND [TotalReturnedResults] <= [TotalHits]");

                            t.HasCheckConstraint("CK_ScreeningRuns_Status", "[Status] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_ScreeningRuns_Timestamps", "[CompletedAtUtc] >= [RequestedAtUtc]");

                            t.HasCheckConstraint("CK_ScreeningRuns_TotalDurationMs", "[TotalDurationMs] >= 0");
                        });
                });

            modelBuilder.Entity("EyRiskScreening.Infrastructure.Persistence.Screening.Entities.ScreeningSourceResultEntity", b =>
                {
                    b.Property<long>("ScreeningSourceResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ScreeningSourceResultId"));

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<byte?>("ErrorCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Hits")
                        .HasColumnType("int");

                    b.Property<byte>("MatchThreshold")
                        .HasColumnType("tinyint");

                    b.Property<int>("ReturnedResults")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("ScreeningSourceResultId");

                    b.HasIndex("RunId", "Source")
                        .IsUnique();

                    b.ToTable("ScreeningSourceResults", "screening", t =>
                        {
                            t.HasCheckConstraint("CK_ScreeningSourceResults_Counts", "[Hits] >= 0 AND [ReturnedResults] >= 0 AND [ReturnedResults] <= [Hits]");

                            t.HasCheckConstraint("CK_ScreeningSourceResults_DurationMs", "[DurationMs] >= 0");

                            t.HasCheckConstraint("CK_ScreeningSourceResults_ErrorCode", "[ErrorCode] IS NULL OR [ErrorCode] IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_ScreeningSourceResults_MatchThreshold", "[MatchThreshold] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_ScreeningSourceResults_Outcome", "([Status] = 0 AND [ErrorCode] IS NULL AND [ErrorMessage] IS NULL) OR ([Status] = 1 AND [ErrorCode] IN (0, 1) AND [ErrorMessage] IS NOT NULL) OR ([Status] = 2 AND [ErrorCode] = 2 AND [ErrorMessage] IS NOT NULL) OR ([Status] = 3 AND [ErrorCode] = 3 AND [ErrorMessage] IS NOT NULL)");

                            t.HasCheckConstraint("CK_ScreeningSourceResults_Source", "[Source] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_ScreeningSourceResults_Status", "[Status] IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_ScreeningSourceResults_UnsuccessfulCounts", "[Status] = 0 OR ([Hits] = 0 AND [ReturnedResults] = 0)");
                        });
                });

            modelBuilder.Entity("EyRiskScreening.Infrastructure.Persistence.Suppliers.SupplierEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualBillingUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTimeOffset>("LastEditedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhysicalAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("LastEditedAtUtc")
                        .IsDescending();

                    b.HasIndex("LegalName");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("Suppliers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Suppliers_AnnualBillingUsd", "[AnnualBillingUsd] >= 0");

                            t.HasCheckConstraint("CK_Suppliers_TaxId", "DATALENGTH([TaxId]) = 11 AND [TaxId] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9]%'");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConcurrencyStamp = "admin-role-v1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ConcurrencyStamp = "analyst-role-v1",
                            Name = "Analyst",
                            NormalizedName = "ANALYST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EyRiskScreening.Infrastructure.Persistence.Screening.Entities.ScreeningMatchEntity", b =>
                {
                    b.HasOne("EyRiskScreening.Infrastructure.Persistence.Screening.Entities.ScreeningSourceResultEntity", "SourceResult")
                        .WithMany("Matches")
                        .HasForeignKey("ScreeningSourceResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceResult");
                });

            modelBuilder.Entity("EyRiskScreening.Infrastructure.Persistence.Screening.Entities.ScreeningRunEntity", b =>
                {
                    b.HasOne("EyRiskScreening.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EyRiskScreening.Infrastructure.Persistence.Screening.Entities.ScreeningSourceResultEntity", b =>
                {
                    b.HasOne("EyRiskScreening.Infrastructure.Persistence.Screening.Entities.ScreeningRunEntity", "Run")
                        .WithMany("Sources")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("EyRiskScreening.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("EyRiskScreening.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EyRiskScreening.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("EyRiskScreening.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EyRiskScreening.Infrastructure.Persistence.Screening.Entities.ScreeningRunEntity", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("EyRiskScreening.Infrastructure.Persistence.Screening.Entities.ScreeningSourceResultEntity", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
